### ISSUE TITLE
Unable to execute ovftool. %!(EXTRA string=Error: Unexpected option:

### ISSUE THREAD

**Issue by karampok** [iancmcc/packer-post-processor-ovftool#1]
Hello, I am getting this error (both in mac os with fusion, and linux with workstation).

=> debian74.amd64.vmware-vmx: Running post-processor: ovftool
Build 'debian74.amd64.vmware-vmx' errored: 1 error(s) occurred:
- Post-processor failed: Unable to execute ovftool. %!(EXTRA string=Error: Unexpected option: packer_debian74.amd64.vmware-vmx_vmware.ova
  Completed with errors
  )

==> Some builds didn't complete successfully and had errors:
--> debian74.amd64.vmware-vmx: 1 error(s) occurred:

Is there anything that i set up wrong?

**Comment by krobertson** [comment]
Fixed this with a PR in #2. It was an issue with handling when compression was 0. You can either set compression to something other than 0, or can build from my fork.

**Comment by iancmcc** [comment]
Closed with merge of #2.
