### ISSUE TITLE
go get and install fails 

### ISSUE THREAD

**Issue by daxgames** [iancmcc/packer-post-processor-ovftool#6]
I know nothing about go or packer plugin development but I need this plugin to work.  Trying to install it I get the below:

gocode $> go get github.com/iancmcc/packer-post-processor-ovftool
# github.com/iancmcc/packer-post-processor-ovftool/ovftool

src/github.com/iancmcc/packer-post-processor-ovftool/ovftool/post-processor.go:21: undefined: packer.ConfigTemplate

I am using Packer 0.7.5.

**Comment by daxgames** [comment]
I rolled my own.  Thanks.

**Comment by ltzany** [comment]
@daxgames can you elaborate what you did? did you just build the binary manually? wondering if you could provide steps if you did it that way.

**Comment by daxgames** [comment]
@jjmiv I used a completely different project and contributed a rather large PR to I that they never merged.  That was 3 years ago so I doubt the work is even still valid.

**Comment by ltzany** [comment]
@daxgames thank you for replying.  i ended up using one of the forks that's more up to date.
